### PR TITLE
Made the not-so-simple ldap_search public.

### PR DESCRIPTION
**Pull request by pwestrich**
Some uses of the LDAP API require it (such as mine), and I don't see much reason for it to be private.

### CODE REVIEW

**Comment by pwestrich** [comment]
So we ran into a couple problems with the ldap_search function after testing it yesterday. In hindsight, we probably should've tested it first, but we didn't expect it to explode at us.

Turns out that the ldap_search function causes the LDAP C library to segfault whenever you pass it a list of attributes to fetch. We're working on a fix for it, and we think we've figured it out.

**Comment by pwestrich** [comment]
I think we've fixed most of the memory errors so far. All tests with this library pass, but when I use it with my own project I'm writing, it sometimes gives a segmentation fault while binding. This tells me we've still got some undefined behavior somewhere, but it's pretty hard to find, and I'm not sure what other places are left to look.

**Comment by rossdylan** [comment]
Wow, thanks so much for picking this up and running with it. Sorry I didn't see this sooner, I think I need to futz with my github notification settings. I've done a precursory review and most of it looks good. However this is a huge PR doing a lot of different things. I'd love it if you could split it up into a couple smaller ones. Another major thing is that you've changed all the indentation from spaces to tabs, which confuses git since you've basically rewritten everything. Again, thanks for submitting this PR, it looks great!

**Comment by coder543** [comment]
Since you didn't respond to this pull request for quite awhile and we were working very heavily on it, I ended up taking the liberty of renaming and republishing it [here](https://crates.io/crates/openldap), to make sure that others in the Rust community could benefit from the time we put into it. I don't think either of us would mind if you wanted to pull in our changes and update `rust-cldap`, but I don't imagine we will have the time or energy to break up this pull request into a cleaner set of PRs. As of `openldap 1.0.2`, we're also now using the `ldap_r` threadsafe library, which is a pretty fundamental change.

**Comment by rossdylan** [comment]
works for me! I'm going to close this out then

**Pull request closed without merging**
